### ISSUE TITLE
Request: PDF of schematics

### ISSUE THREAD

**Issue by Fliptron** [EliMattingly22/Simple_Impedance_Analyzer#1]
Hi Eli,
Kicad is not used by everybody. Please include a PDF for the schematic, that is updated whenever the schematic is updated.
Thanks

**Comment by EliMattingly22** [comment]
Good suggestion. PDF added for current revision (V2 revB) in its respective directory. Future revisions will have PDFs
[Impedance_Analyzer_V2.pdf](https://github.com/EliMattingly22/Simple_Impedance_Analyzer/blob/main/Impedance_Analyzer_V2_KiCAD/Impedance_Analyzer_V2.pdf)
